# Generated by Django 4.1.2 on 2022-10-21 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooom',
            new_name='Room',
        ),
    ]
